###
POST http://localhost:3001/api/book/createbook
Content-Type: application/json

{
    "BookName":"EAST OF EDEN",
    "Auther":"JOHN STEINBECK",
    "Quantity":10,
    "Price":350.00,
    "PublishDate":"07/01/1952"
}

###
POST http://localhost:3001/api/book/updatebook
Content-Type: application/json

{
    "BookIdentity":"29334678-d06d-467d-b0f7-68de908b0f85",
    "BookName":"THE SUN ALSO RISES",
    "Auther":"ERNEST HEMINGWAY",
    "Quantity":50,
    "Price":500.00,
    "PublishDate":"07/01/1926"
}

###
POST http://localhost:3001/api/book/removebook
Content-Type: application/json

{
    "BookIdentity":"0acb3ebc-38f0-49fd-b14a-972f4225e9fd"
}